# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2
jobs:
  build:
    docker:
      - image: sennerholm/google-cloud-sdk-terraform

    steps:
      - checkout

      - run: 
         name: Checking environment
         command: env

      - setup_remote_docker

      - run: 
          name: Build and verify artifact
          command: scripts/buildverify-artifact.sh ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_BUILD_NUM}
      - run:
          name: Authenticate to GCP
          command: source scripts/common.sh; gcpAuthenticate ${GOOGLE_AUTH} ${GOOGLE_PROJECT_ID} ${GOOGLE_COMPUTE_ZONE}


      - run:
          name: Persist artifacts
          command: scripts/persist-artifact.sh ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_BUILD_NUM} eu.gcr.io/${GOOGLE_PROJECT_ID}
      - run: echo ${CIRCLE_BUILD_NUM} > circleci-build-number.txt

      - persist_to_workspace:
          root: .
          paths:
            - scripts
            - circleci-build-number.txt
            

  fast_test:
    docker:
      - image: sennerholm/google-cloud-sdk-terraform

    steps:   
      - attach_workspace:
          at: .
     
      - run: 
         name: Checking environment
         command: env
      - run: 
         name: Checking dirs
         command: ls -l . scripts
      - run:
          name: Clone and update Terraform infrastructure repo
          command: bash -x scripts/clone-and-update-infrastructure.sh ${CIRCLE_SHA1} `cat circleci-build-number.txt` 
          
      - run:
          name: Deploy application and test pods
          command: |
            cd terraform-infrastructure-live/gce_account/europe-west1/fast/todo-backend-fast
            terragrunt apply -auto-approve
            kubectl  --namespace=test-todo-backend logs -f po/todo-backend-`cat circleci-build-number.txt`
  
  deploy_stage:
    docker:
      - image: sennerholm/google-cloud-sdk-terraform

    steps:
      - run: 
          name: Checking environment
          command: env
      - run:
          name: Clone Terraform infrastructure
          command: echo clone repo

      - run:
          name: Update repo artifact to new version
          command: echo Update ref

      - run:
          name: Deploy application 
          command: echo run terraform to deploy pod

  deploy_prod:
    docker:
      - image: sennerholm/google-cloud-sdk-terraform

    steps:
      - run: 
          name: Checking environment
          command: env
      - run:
          name: Clone Terraform infrastructure
          command: echo clone repo

      - run:
          name: Update repo artifact to new version
          command: echo Update ref

      - run:
          name: Deploy application 
          command: echo run terraform to deploy pod

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context: org-global      
      - fast_test:
          context: org-global      
          requires:
            - build
      - deploy_stage:
          context: org-global      
          requires:
            - fast_test
      - approve_prod:
          type: approval
          filters:
            branches:
              only: master
          requires:
              - deploy_stage
      - deploy_prod:
          context: org-global            
          filters:
            branches:
              only: master
          requires:
            - approve_prod
